// Copyright 2026 The Kruise Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: api/security/v1/trafficpolicy.proto

package securityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrafficPolicy_Scope int32

const (
	TrafficPolicy_GLOBAL            TrafficPolicy_Scope = 0
	TrafficPolicy_NAMESPACE         TrafficPolicy_Scope = 1
	TrafficPolicy_WORKLOAD_SELECTOR TrafficPolicy_Scope = 2
)

// Enum value maps for TrafficPolicy_Scope.
var (
	TrafficPolicy_Scope_name = map[int32]string{
		0: "GLOBAL",
		1: "NAMESPACE",
		2: "WORKLOAD_SELECTOR",
	}
	TrafficPolicy_Scope_value = map[string]int32{
		"GLOBAL":            0,
		"NAMESPACE":         1,
		"WORKLOAD_SELECTOR": 2,
	}
)

func (x TrafficPolicy_Scope) Enum() *TrafficPolicy_Scope {
	p := new(TrafficPolicy_Scope)
	*p = x
	return p
}

func (x TrafficPolicy_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficPolicy_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_api_security_v1_trafficpolicy_proto_enumTypes[0].Descriptor()
}

func (TrafficPolicy_Scope) Type() protoreflect.EnumType {
	return &file_api_security_v1_trafficpolicy_proto_enumTypes[0]
}

func (x TrafficPolicy_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficPolicy_Scope.Descriptor instead.
func (TrafficPolicy_Scope) EnumDescriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 0}
}

type TrafficPolicy_Action int32

const (
	TrafficPolicy_ALLOW TrafficPolicy_Action = 0
	TrafficPolicy_DENY  TrafficPolicy_Action = 1
)

// Enum value maps for TrafficPolicy_Action.
var (
	TrafficPolicy_Action_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
	}
	TrafficPolicy_Action_value = map[string]int32{
		"ALLOW": 0,
		"DENY":  1,
	}
)

func (x TrafficPolicy_Action) Enum() *TrafficPolicy_Action {
	p := new(TrafficPolicy_Action)
	*p = x
	return p
}

func (x TrafficPolicy_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficPolicy_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_api_security_v1_trafficpolicy_proto_enumTypes[1].Descriptor()
}

func (TrafficPolicy_Action) Type() protoreflect.EnumType {
	return &file_api_security_v1_trafficpolicy_proto_enumTypes[1]
}

func (x TrafficPolicy_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficPolicy_Action.Descriptor instead.
func (TrafficPolicy_Action) EnumDescriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 1}
}

type TrafficPolicy_Protocol int32

const (
	TrafficPolicy_ALL  TrafficPolicy_Protocol = 0
	TrafficPolicy_TCP  TrafficPolicy_Protocol = 1
	TrafficPolicy_UDP  TrafficPolicy_Protocol = 2
	TrafficPolicy_ICMP TrafficPolicy_Protocol = 3
	TrafficPolicy_SCTP TrafficPolicy_Protocol = 4
)

// Enum value maps for TrafficPolicy_Protocol.
var (
	TrafficPolicy_Protocol_name = map[int32]string{
		0: "ALL",
		1: "TCP",
		2: "UDP",
		3: "ICMP",
		4: "SCTP",
	}
	TrafficPolicy_Protocol_value = map[string]int32{
		"ALL":  0,
		"TCP":  1,
		"UDP":  2,
		"ICMP": 3,
		"SCTP": 4,
	}
)

func (x TrafficPolicy_Protocol) Enum() *TrafficPolicy_Protocol {
	p := new(TrafficPolicy_Protocol)
	*p = x
	return p
}

func (x TrafficPolicy_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficPolicy_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_security_v1_trafficpolicy_proto_enumTypes[2].Descriptor()
}

func (TrafficPolicy_Protocol) Type() protoreflect.EnumType {
	return &file_api_security_v1_trafficpolicy_proto_enumTypes[2]
}

func (x TrafficPolicy_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficPolicy_Protocol.Descriptor instead.
func (TrafficPolicy_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 2}
}

// One compiled TrafficPolicy/GlobalTrafficPolicy, retaining both directions.
// Selection and explicit attachment are resolved before publication.
type TrafficPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identity, e.g. trafficpolicy/demo/internet or
	// globaltrafficpolicy/platform-baseline.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Source namespace; required for NAMESPACE scope.
	// Empty for a cluster-scoped GlobalTrafficPolicy.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Nonnegative; lower values are evaluated first.
	// The compiler materializes the source default (1000).
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Absent = direction not configured; present with no rules = no rule matches.
	Ingress *TrafficPolicy_PolicyRule `protobuf:"bytes,4,opt,name=ingress,proto3" json:"ingress,omitempty"`
	Egress  *TrafficPolicy_PolicyRule `protobuf:"bytes,5,opt,name=egress,proto3" json:"egress,omitempty"`
	// GLOBAL: applies to all workloads; NAMESPACE: applies within namespace.
	// WORKLOAD_SELECTOR: applies through control-plane-generated workload refs,
	// including selector-based GlobalTrafficPolicies. Do not infer scope from name.
	Scope         TrafficPolicy_Scope `protobuf:"varint,6,opt,name=scope,proto3,enum=io.kruise.agentio.security.v1.TrafficPolicy_Scope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy) Reset() {
	*x = TrafficPolicy{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy) ProtoMessage() {}

func (x *TrafficPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy.ProtoReflect.Descriptor instead.
func (*TrafficPolicy) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrafficPolicy) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TrafficPolicy) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TrafficPolicy) GetIngress() *TrafficPolicy_PolicyRule {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *TrafficPolicy) GetEgress() *TrafficPolicy_PolicyRule {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *TrafficPolicy) GetScope() TrafficPolicy_Scope {
	if x != nil {
		return x.Scope
	}
	return TrafficPolicy_GLOBAL
}

// An IPv4 or IPv6 network prefix.
type TrafficPolicy_Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network address in 4-byte IPv4 or 16-byte IPv6 form, with host bits zero.
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Prefix length: 0..32 for IPv4, 0..128 for IPv6.
	Length        uint32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_Address) Reset() {
	*x = TrafficPolicy_Address{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_Address) ProtoMessage() {}

func (x *TrafficPolicy_Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_Address.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_Address) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TrafficPolicy_Address) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TrafficPolicy_Address) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type TrafficPolicy_PolicyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First matching rule wins, in declaration order.
	// No match continues to the next policy; no per-policy default.
	Rules         []*TrafficPolicy_Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_PolicyRule) Reset() {
	*x = TrafficPolicy_PolicyRule{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_PolicyRule) ProtoMessage() {}

func (x *TrafficPolicy_PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_PolicyRule.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_PolicyRule) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TrafficPolicy_PolicyRule) GetRules() []*TrafficPolicy_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type TrafficPolicy_Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ALLOW/DENY correspond to source allow/reject; the compiler sets the action.
	// The protobuf default is ALLOW. Unknown values are invalid.
	Action TrafficPolicy_Action `protobuf:"varint,1,opt,name=action,proto3,enum=io.kruise.agentio.security.v1.TrafficPolicy_Action" json:"action,omitempty"`
	// Required presence. Explicit {} matches all traffic.
	Match         *TrafficPolicy_Match `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_Rule) Reset() {
	*x = TrafficPolicy_Rule{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_Rule) ProtoMessage() {}

func (x *TrafficPolicy_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_Rule.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_Rule) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 2}
}

func (x *TrafficPolicy_Rule) GetAction() TrafficPolicy_Action {
	if x != nil {
		return x.Action
	}
	return TrafficPolicy_ALLOW
}

func (x *TrafficPolicy_Rule) GetMatch() *TrafficPolicy_Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type TrafficPolicy_Match struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dimensions are ANDed; values within each dimension are ORed.
	// Empty address list = unconstrained.
	// Resolve peers in the control plane. If an explicitly configured source
	// or destination peer list resolves to no addresses, omit the entire Rule
	// while retaining the configured direction, even if no rules remain.
	// Validate Address byte/prefix lengths and normalize host bits.
	SourceIps      []*TrafficPolicy_Address `protobuf:"bytes,1,rep,name=source_ips,json=sourceIps,proto3" json:"source_ips,omitempty"`
	DestinationIps []*TrafficPolicy_Address `protobuf:"bytes,2,rep,name=destination_ips,json=destinationIps,proto3" json:"destination_ips,omitempty"`
	// Empty = any protocol/port. Entries are ORed.
	Ports         []*TrafficPolicy_PortMatch `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_Match) Reset() {
	*x = TrafficPolicy_Match{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_Match) ProtoMessage() {}

func (x *TrafficPolicy_Match) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_Match.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_Match) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 3}
}

func (x *TrafficPolicy_Match) GetSourceIps() []*TrafficPolicy_Address {
	if x != nil {
		return x.SourceIps
	}
	return nil
}

func (x *TrafficPolicy_Match) GetDestinationIps() []*TrafficPolicy_Address {
	if x != nil {
		return x.DestinationIps
	}
	return nil
}

func (x *TrafficPolicy_Match) GetPorts() []*TrafficPolicy_PortMatch {
	if x != nil {
		return x.Ports
	}
	return nil
}

type TrafficPolicy_PortMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unknown protocol values are invalid.
	// ALL with a port constraint only matches protocols with destination ports.
	Protocol TrafficPolicy_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=io.kruise.agentio.security.v1.TrafficPolicy_Protocol" json:"protocol,omitempty"`
	// Inclusive destination port bounds, when present, must be in 1..65535.
	// Only port: match that single port.
	// Only end_port: match 1..end_port.
	// Both: match port..end_port, requiring port <= end_port.
	// Neither: any port (no port test). ICMP requires both fields absent.
	Port          *uint32 `protobuf:"varint,2,opt,name=port,proto3,oneof" json:"port,omitempty"`
	EndPort       *uint32 `protobuf:"varint,3,opt,name=end_port,json=endPort,proto3,oneof" json:"end_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy_PortMatch) Reset() {
	*x = TrafficPolicy_PortMatch{}
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy_PortMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy_PortMatch) ProtoMessage() {}

func (x *TrafficPolicy_PortMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_security_v1_trafficpolicy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy_PortMatch.ProtoReflect.Descriptor instead.
func (*TrafficPolicy_PortMatch) Descriptor() ([]byte, []int) {
	return file_api_security_v1_trafficpolicy_proto_rawDescGZIP(), []int{0, 4}
}

func (x *TrafficPolicy_PortMatch) GetProtocol() TrafficPolicy_Protocol {
	if x != nil {
		return x.Protocol
	}
	return TrafficPolicy_ALL
}

func (x *TrafficPolicy_PortMatch) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *TrafficPolicy_PortMatch) GetEndPort() uint32 {
	if x != nil && x.EndPort != nil {
		return *x.EndPort
	}
	return 0
}

var File_api_security_v1_trafficpolicy_proto protoreflect.FileDescriptor

const file_api_security_v1_trafficpolicy_proto_rawDesc = "" +
	"\n" +
	"#api/security/v1/trafficpolicy.proto\x12\x1dio.kruise.agentio.security.v1\"\xd0\t\n" +
	"\rTrafficPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12Q\n" +
	"\aingress\x18\x04 \x01(\v27.io.kruise.agentio.security.v1.TrafficPolicy.PolicyRuleR\aingress\x12O\n" +
	"\x06egress\x18\x05 \x01(\v27.io.kruise.agentio.security.v1.TrafficPolicy.PolicyRuleR\x06egress\x12H\n" +
	"\x05scope\x18\x06 \x01(\x0e22.io.kruise.agentio.security.v1.TrafficPolicy.ScopeR\x05scope\x1a;\n" +
	"\aAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x16\n" +
	"\x06length\x18\x02 \x01(\rR\x06length\x1aU\n" +
	"\n" +
	"PolicyRule\x12G\n" +
	"\x05rules\x18\x01 \x03(\v21.io.kruise.agentio.security.v1.TrafficPolicy.RuleR\x05rules\x1a\x9d\x01\n" +
	"\x04Rule\x12K\n" +
	"\x06action\x18\x01 \x01(\x0e23.io.kruise.agentio.security.v1.TrafficPolicy.ActionR\x06action\x12H\n" +
	"\x05match\x18\x02 \x01(\v22.io.kruise.agentio.security.v1.TrafficPolicy.MatchR\x05match\x1a\x89\x02\n" +
	"\x05Match\x12S\n" +
	"\n" +
	"source_ips\x18\x01 \x03(\v24.io.kruise.agentio.security.v1.TrafficPolicy.AddressR\tsourceIps\x12]\n" +
	"\x0fdestination_ips\x18\x02 \x03(\v24.io.kruise.agentio.security.v1.TrafficPolicy.AddressR\x0edestinationIps\x12L\n" +
	"\x05ports\x18\x03 \x03(\v26.io.kruise.agentio.security.v1.TrafficPolicy.PortMatchR\x05ports\x1a\xad\x01\n" +
	"\tPortMatch\x12Q\n" +
	"\bprotocol\x18\x01 \x01(\x0e25.io.kruise.agentio.security.v1.TrafficPolicy.ProtocolR\bprotocol\x12\x17\n" +
	"\x04port\x18\x02 \x01(\rH\x00R\x04port\x88\x01\x01\x12\x1e\n" +
	"\bend_port\x18\x03 \x01(\rH\x01R\aendPort\x88\x01\x01B\a\n" +
	"\x05_portB\v\n" +
	"\t_end_port\"9\n" +
	"\x05Scope\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x00\x12\r\n" +
	"\tNAMESPACE\x10\x01\x12\x15\n" +
	"\x11WORKLOAD_SELECTOR\x10\x02\"\x1d\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\"9\n" +
	"\bProtocol\x12\a\n" +
	"\x03ALL\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\a\n" +
	"\x03UDP\x10\x02\x12\b\n" +
	"\x04ICMP\x10\x03\x12\b\n" +
	"\x04SCTP\x10\x04B:Z8github.com/openkruise/agentio/api/security/v1;securityv1b\x06proto3"

var (
	file_api_security_v1_trafficpolicy_proto_rawDescOnce sync.Once
	file_api_security_v1_trafficpolicy_proto_rawDescData []byte
)

func file_api_security_v1_trafficpolicy_proto_rawDescGZIP() []byte {
	file_api_security_v1_trafficpolicy_proto_rawDescOnce.Do(func() {
		file_api_security_v1_trafficpolicy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_security_v1_trafficpolicy_proto_rawDesc), len(file_api_security_v1_trafficpolicy_proto_rawDesc)))
	})
	return file_api_security_v1_trafficpolicy_proto_rawDescData
}

var file_api_security_v1_trafficpolicy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_security_v1_trafficpolicy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_security_v1_trafficpolicy_proto_goTypes = []any{
	(TrafficPolicy_Scope)(0),         // 0: io.kruise.agentio.security.v1.TrafficPolicy.Scope
	(TrafficPolicy_Action)(0),        // 1: io.kruise.agentio.security.v1.TrafficPolicy.Action
	(TrafficPolicy_Protocol)(0),      // 2: io.kruise.agentio.security.v1.TrafficPolicy.Protocol
	(*TrafficPolicy)(nil),            // 3: io.kruise.agentio.security.v1.TrafficPolicy
	(*TrafficPolicy_Address)(nil),    // 4: io.kruise.agentio.security.v1.TrafficPolicy.Address
	(*TrafficPolicy_PolicyRule)(nil), // 5: io.kruise.agentio.security.v1.TrafficPolicy.PolicyRule
	(*TrafficPolicy_Rule)(nil),       // 6: io.kruise.agentio.security.v1.TrafficPolicy.Rule
	(*TrafficPolicy_Match)(nil),      // 7: io.kruise.agentio.security.v1.TrafficPolicy.Match
	(*TrafficPolicy_PortMatch)(nil),  // 8: io.kruise.agentio.security.v1.TrafficPolicy.PortMatch
}
var file_api_security_v1_trafficpolicy_proto_depIdxs = []int32{
	5,  // 0: io.kruise.agentio.security.v1.TrafficPolicy.ingress:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.PolicyRule
	5,  // 1: io.kruise.agentio.security.v1.TrafficPolicy.egress:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.PolicyRule
	0,  // 2: io.kruise.agentio.security.v1.TrafficPolicy.scope:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.Scope
	6,  // 3: io.kruise.agentio.security.v1.TrafficPolicy.PolicyRule.rules:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.Rule
	1,  // 4: io.kruise.agentio.security.v1.TrafficPolicy.Rule.action:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.Action
	7,  // 5: io.kruise.agentio.security.v1.TrafficPolicy.Rule.match:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.Match
	4,  // 6: io.kruise.agentio.security.v1.TrafficPolicy.Match.source_ips:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.Address
	4,  // 7: io.kruise.agentio.security.v1.TrafficPolicy.Match.destination_ips:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.Address
	8,  // 8: io.kruise.agentio.security.v1.TrafficPolicy.Match.ports:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.PortMatch
	2,  // 9: io.kruise.agentio.security.v1.TrafficPolicy.PortMatch.protocol:type_name -> io.kruise.agentio.security.v1.TrafficPolicy.Protocol
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_security_v1_trafficpolicy_proto_init() }
func file_api_security_v1_trafficpolicy_proto_init() {
	if File_api_security_v1_trafficpolicy_proto != nil {
		return
	}
	file_api_security_v1_trafficpolicy_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_security_v1_trafficpolicy_proto_rawDesc), len(file_api_security_v1_trafficpolicy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_security_v1_trafficpolicy_proto_goTypes,
		DependencyIndexes: file_api_security_v1_trafficpolicy_proto_depIdxs,
		EnumInfos:         file_api_security_v1_trafficpolicy_proto_enumTypes,
		MessageInfos:      file_api_security_v1_trafficpolicy_proto_msgTypes,
	}.Build()
	File_api_security_v1_trafficpolicy_proto = out.File
	file_api_security_v1_trafficpolicy_proto_goTypes = nil
	file_api_security_v1_trafficpolicy_proto_depIdxs = nil
}
